/**
 * Webinar seed-data generator.
 *
 * Responsibilities:
 *  1. Re-export the single `normalize()` (see shared/normalize.ts) so seed-time
 *     and run-time normalization can never drift.
 *  2. Emit build-consumed artifacts from the authoritative CSVs:
 *       - shared/generated/parent-orgs.generated.ts  (select options + Zod enum)
 *       - public/webinar/systems/<parent_org_id>.json (client combobox candidates)
 *  3. `--regenerate` (maintenance only): rebuild data/systems.csv from
 *     data/parent_orgs.csv using the division templates. NOT run by default —
 *     the committed systems.csv is curated and authoritative.
 *
 * Run: pnpm gen:webinar   (cwd = project root)
 */
import * as fs from "fs"
import * as path from "path"
import { normalize } from "../shared/normalize"
import { US_STATES } from "../shared/enums"

export { normalize } from "../shared/normalize"

const ROOT = process.cwd()
const DATA_DIR = path.join(ROOT, "data")
const GEN_DIR = path.join(ROOT, "shared", "generated")
const PUBLIC_SYS_DIR = path.join(ROOT, "public", "webinar", "systems")

// ---------- CSV (RFC 4180-ish) ----------
export function parseCsv(text: string): string[][] {
  const rows: string[][] = []
  let field = ""
  let row: string[] = []
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') {
          field += '"'
          i++
        } else inQuotes = false
      } else field += ch
    } else if (ch === '"') inQuotes = true
    else if (ch === ",") {
      row.push(field)
      field = ""
    } else if (ch === "\r") {
      /* skip */
    } else if (ch === "\n") {
      row.push(field)
      rows.push(row)
      row = []
      field = ""
    } else field += ch
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field)
    rows.push(row)
  }
  return rows
}

function csvEscape(v: string): string {
  return /[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v
}

function rowsToObjects(rows: string[][]): Record<string, string>[] {
  const [header, ...body] = rows
  return body
    .filter((r) => r.length > 1 || (r.length === 1 && r[0].trim() !== ""))
    .map((r) => Object.fromEntries(header.map((h, i) => [h.trim(), (r[i] ?? "").trim()])))
}

// ---------- Types ----------
export interface ParentOrg {
  parent_org_id: string
  canonical_name: string
  short_name: string
  has_state_affiliates: string
  state_naming_template: string
  divisions: string
  acronyms: string
  notes: string
  confidence: string
}

export interface SystemRow {
  system_id: string
  parent_org_id: string
  canonical_name: string
  division: string
  level: string
  state: string
  state_abbr: string
  normalized_name: string
  aliases: string[]
  verified: string
  source: string
}

// ---------- Readers ----------
export function readParentOrgs(): ParentOrg[] {
  const text = fs.readFileSync(path.join(DATA_DIR, "parent_orgs.csv"), "utf8")
  return rowsToObjects(parseCsv(text)) as unknown as ParentOrg[]
}

export function readSystems(): SystemRow[] {
  const text = fs.readFileSync(path.join(DATA_DIR, "systems.csv"), "utf8")
  return rowsToObjects(parseCsv(text)).map((o) => ({
    ...(o as unknown as SystemRow),
    aliases: (o.aliases || "").split("|").map((a) => a.trim()).filter(Boolean),
  }))
}

// ---------- Emit: parent-orgs.generated.ts ----------
function writeParentOrgsGenerated(orgs: ParentOrg[]): void {
  const items = orgs.map((o) => ({ id: o.parent_org_id, label: o.canonical_name, shortName: o.short_name }))
  const body = `// AUTO-GENERATED by scripts/generate-systems.ts — do not edit by hand.
// Source: data/parent_orgs.csv. Regenerate with: pnpm gen:webinar
export interface ParentOrgOption { id: string; label: string; shortName: string }
export const PARENT_ORGS: readonly ParentOrgOption[] = ${JSON.stringify(items, null, 2)}
export const PARENT_ORG_IDS = PARENT_ORGS.map((o) => o.id) as [string, ...string[]]
`
  fs.mkdirSync(GEN_DIR, { recursive: true })
  fs.writeFileSync(path.join(GEN_DIR, "parent-orgs.generated.ts"), body)
}

// ---------- Emit: per-org client JSON ----------
function writePerOrgJson(systems: SystemRow[]): number {
  fs.mkdirSync(PUBLIC_SYS_DIR, { recursive: true })
  const byOrg = new Map<string, SystemRow[]>()
  for (const s of systems) {
    if (!byOrg.has(s.parent_org_id)) byOrg.set(s.parent_org_id, [])
    byOrg.get(s.parent_org_id)!.push(s)
  }
  for (const [orgId, rows] of byOrg) {
    const payload = rows.map((r) => ({
      systemId: r.system_id,
      canonicalName: r.canonical_name,
      normalizedName: r.normalized_name || normalize(r.canonical_name),
      aliases: r.aliases,
      division: r.division,
      level: r.level,
      state: r.state,
      stateAbbr: r.state_abbr,
    }))
    fs.writeFileSync(path.join(PUBLIC_SYS_DIR, `${orgId}.json`), JSON.stringify(payload))
  }
  return byOrg.size
}

// ---------- Maintenance: regenerate systems.csv from templates ----------
function parseDivisions(org: ParentOrg): Array<{ label: string; template: string }> {
  if (org.divisions && org.divisions.includes("::")) {
    return org.divisions.split("|").map((pair) => {
      const [label, template] = pair.split("::")
      return { label: label.trim(), template: (template ?? "").trim() }
    })
  }
  // Empty / non-template divisions => single record per state using the org template.
  return [{ label: "Open", template: org.state_naming_template || `${org.canonical_name} {State}` }]
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")
}

export function generateSystemsCsv(orgs: ParentOrg[]): string {
  const header = "system_id,parent_org_id,canonical_name,division,level,state,state_abbr,normalized_name,aliases,verified,source"
  const lines = [header]
  const states = US_STATES.filter((s) => s.abbr !== "XX")
  for (const org of orgs) {
    if (org.has_state_affiliates !== "yes" || !org.state_naming_template) continue
    for (const div of parseDivisions(org)) {
      if (!div.template) continue
      for (const st of states) {
        const canonical = div.template.replace(/\{State\}/g, st.name)
        const aliases = [canonical, `${canonical} Pageant`, `${st.name} ${org.short_name}`]
        const id = `${org.parent_org_id}-${st.abbr.toLowerCase()}-${slug(div.label)}`
        lines.push(
          [
            id,
            org.parent_org_id,
            canonical,
            div.label,
            "State",
            st.name,
            st.abbr,
            normalize(canonical),
            aliases.join("|"),
            "false",
            "generated",
          ]
            .map((v) => csvEscape(String(v)))
            .join(","),
        )
      }
    }
  }
  return lines.join("\n") + "\n"
}

// ---------- Main ----------
function main(): void {
  const orgs = readParentOrgs()
  writeParentOrgsGenerated(orgs)
  const systems = readSystems()
  const orgCount = writePerOrgJson(systems)

  if (process.argv.includes("--regenerate")) {
    const csv = generateSystemsCsv(orgs)
    fs.writeFileSync(path.join(DATA_DIR, "systems.csv"), csv)
    console.log("[regenerate] rewrote data/systems.csv from templates")
  }

  console.log(
    `Generated parent-orgs.generated.ts (${orgs.length} orgs) and ${orgCount} per-org system JSON files (${systems.length} systems).`,
  )
}

// Run only when executed directly (not when imported by the Lambda/tests).
const invokedDirectly = process.argv[1] && /generate-systems\.(ts|js)$/.test(process.argv[1])
if (invokedDirectly) main()
